server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/couriertracking
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


springdoc:
  packagesToScan: com.couriertracking
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui