server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/couriertracking
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
feign:
  client:
    config:
      courier-service:
        name: courier-service
        url: http://localhost:8081
      store-service:
        name: store-service
        url: http://localhost:8085/stores
      evaluation-service:
        name: evaluation-service
        url: http://localhost:8083

springdoc:
  packagesToScan: com.couriertracking
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui